### ISSUE TITLE
Project not stripped for portability

### ISSUE THREAD

**Issue by AlexStormwood** [luketurnerdev/codevelop-unity-tutorial#1]
Unity projects designed to be shared via ZIP files should be stripped down to their bare essentials. Library & Temp & other folders are not necessary and are regenerated every time Unity runs that project, and Packages are downloaded as soon as the manifest file is processed.

Essential folders for 2019.3.x projects are: 
- Assets
- Packages
- Project Settings

If a ZIP file has only those folders, everything will still work and you'd be sharing a smaller file. ZIPping only these folders will trim your ZIP file down from the current 47MB to 17MB, and make it much easier for students to download.

**Comment by luketurnerdev** [comment]
Thanks for pointing this out Alex :) I have stripped the project back and pushed the latest version. I have tested it on my machine and it still seems to open fine.
